### ISSUE TITLE
Gatsby Umbrella Issue

### ISSUE THREAD

**Issue by GoPro16** [Availity/availity-react#251]
## Gatsby Docs Site

This is a major overhaul to how we write docs and the goal is to eventually lose storybook or integrate it seamlessly into the gatsby docs.

Target Structure:
https://availity.github.io/availity-react will point to the gatsby site.
https://availity.github.io/availity-react/storybook will point to the storybook.

TODO - Currently the [`App Icon`](https://availity.github.io/availity-react/components/app-icon) page is using mdx and rendering the app icon, however the format is not finalized. Once a finalized structure is finished, we can start on getting all of these moved over.

Refactor Todos ( Not ready ):
- [x] [`App Icon`](https://availity.github.io/availity-react/components/app-icon)
- [x] [`Authorize`](https://availity.github.io/availity-react/components/authorize)
- [x] [`Avatar`](https://availity.github.io/availity-react/components/avatar)
- [x] [`Breadcrumbs`](https://availity.github.io/availity-react/components/breadcrumbs)
- [x] [`Date`](https://availity.github.io/availity-react/components/date)
- [x] [`Favorites`](https://availity.github.io/availity-react/components/favorites)
- [x] [`Feature`](https://availity.github.io/availity-react/components/feature)
- [x] [`Feedback`](https://availity.github.io/availity-react/components/feedback)
- [x] [`Form`](https://availity.github.io/availity-react/components/form)
- [x] [`Hooks`](https://availity.github.io/availity-react/components/hooks)
- [x] [`Icon`](https://availity.github.io/availity-react/components/icon)
- [x] [`Link`](https://availity.github.io/availity-react/components/link)
- [x] [`List Group`](https://availity.github.io/availity-react/components/list-group)
- [x] [`List Group Item`](https://availity.github.io/availity-react/components/list-group-item)
- [x] [`Page Header`](https://availity.github.io/availity-react/components/page-header)
- [x] [`Pagination`](https://availity.github.io/availity-react/components/pagination)
- [x] [`Progress`](https://availity.github.io/availity-react/components/progress)
- [x] [`Select`](https://availity.github.io/availity-react/components/select)
- [x] [`Spaces`](https://availity.github.io/availity-react/components/spaces)
- [x] [`Step Wizard`](https://availity.github.io/availity-react/components/step-wizard)
- [x] [`Training Link`](https://availity.github.io/availity-react/components/training-link)
- [x] [`Typography`](https://availity.github.io/availity-react/components/typography)
- [x] [`Upload`](https://availity.github.io/availity-react/components/upload)

Omitted components:
- reactstrap-validation-select - moving to `reactstrap-validation`
- reactstrap-validation-date - moving to `reactstrap-validation`
- payer-logo - Shouldn't be used due to new `spaces` component

Gatsby Theme Todos ( to be tracking on the gatsby repo ):
- [x] Dynamic Scopes for live editor
- [x] XHR Mock support
- [x] Heading level 2 section navigation
